[tools]
awscli = "latest"
aws-vault = "v7.2.0"
azure = "latest"
azure-kubelogin = "latest"
buf = "latest"
chezmoi = "latest"
cosign = "latest"
fd = "latest"
flux2 = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
golangci-lint = "latest"
hadolint = "latest"
helm = "latest"
hugo-extended = "latest"
jq = "latest"
k3d = "latest"
k3s = "latest"
k3sup = "latest"
k9s = "latest"
krew = "latest"
kubectl = "latest"
kubectx = "latest"
kubens = "latest"
kustomize = "latest"
lazygit = "latest"
neovim = "latest"
node = "latest"
portless = "latest"
ripgrep = "latest"
sops = "latest"
terraform = "latest"
trivy = "latest"
uv = "latest"
watchexec = "latest"
yazi = "latest"
zellij = "latest"
#yq = "latest"
