# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/apps/vicinae.conf

# General settings
general{
    # Reduce gap size
    gaps_in = 0
    gaps_out = 0
    # Use scrolling layout with hyprscrolling plugin
    layout = scrolling
}

# Configure scrolling layout
scrolling {
    column_width = 0.5
    fullscreen_on_one_column = true
    focus_fit_method = 0
    follow_focus = false
  }

# Use master layout for workspace 4
workspace = 4, layout:master

# set master (left) area to 70%
master {
    mfact = 0.70          # 0.7 = 70% for master, 30% for stack
    orientation = left    # or right / top / bottom if you prefer
    new_on_top = true     # whether a newly open window should be on the top of the stack
    new_status = master   # new window becomes master
}
