return {
  {
    "mason-org/mason.nvim",
    opts = {
      ensure_installed = {
        "buf",
        "gci",
        "goimports",
        "golangci-lint",
        "golangci-lint-langserver",
        "gopls",
        "hadolint",
        "helm-ls",
        "isort",
        "jq",
        "json-lsp",
        "jsonlint",
        "kube-linter",
        "lua-language-server",
        "markdownlint",
        "pyrefly",
        "python-lsp-server",
        "stylua",
        "shellcheck",
        "shfmt",
        "flake8",
        "yaml-language-server",
        "yamllint",
      },
    },
  },
}
