return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "css",
      "diff",
      "help",
      "gitignore",
      "go",
      "gomod",
      "gosum",
      "gotmpl",
      "gowork",
      "html",
      "http",
      "html_tags",
      "http",
      "javascript",
      "jsdoc",
      "json",
      "jsonc",
      "kulala_http",
      "lua",
      "luadoc",
      "luap",
      "markdown",
      "markdown_inline",
      "printf",
      "proto",
      "python",
      "query",
      "regex",
      "sql",
      "terraform",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "xml",
      "yaml",
    },
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = false, -- Disable legacy
    },
    indent = { enable = true },
  },
}
