return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "buf",
        "buf-language-server",
        "gci",
        "goimports",
        "golangci-lint",
        "golangci-lint-langserver",
        "gopls",
        "hadolint",
        "helm-ls",
        "isort",
        "jq",
        "kube-linter",
        "lua-language-server",
        "markdownlint",
        "pyrefly",
        "stylua",
        "shellcheck",
        "shfmt",
        "flake8",
        "yaml-language-server",
        "yamllint",
      },
    },
  },
}
